const PROP_KEY='borshaProperties';
const BOT_KEY='borshaChatbotSettings';
const defaultProperties=[
{id:1,title:'Azure Hills Villa',location:'Gulshan, Dhaka',type:'Villa',status:'For Sale',price:1250000,beds:5,rooms:8,baths:5,size:'4,500 Sq Ft',img:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=85',description:'A contemporary luxury villa with generous living spaces and premium finishes.',amenities:'Parking, Garden, Smart entry, Balcony'},
{id:2,title:'Skyline Residence',location:'Banani, Dhaka',type:'Apartment',status:'For Sale',price:680000,beds:3,rooms:5,baths:3,size:'2,200 Sq Ft',img:'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=900&q=85',description:'A modern apartment with city views and convenient access to Banani.',amenities:'Parking, Lift, Security, Balcony'},
{id:3,title:'Warmwood Family Home',location:'Bashundhara, Dhaka',type:'Home',status:'For Rent',price:2500,beds:4,rooms:7,baths:4,size:'3,200 Sq Ft',img:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=85',description:'A warm family home with spacious rooms and a comfortable layout.',amenities:'Parking, Garden, Security'},
{id:4,title:'Palm Court Estate',location:'Mohammadpur, Dhaka',type:'Villa',status:'For Sale',price:950000,beds:4,rooms:7,baths:4,size:'3,000 Sq Ft',img:'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=900&q=85',description:'A refined villa with comfortable family spaces and modern finishes.',amenities:'Parking, Garden, Balcony, Security'},
{id:5,title:'Lakeview Heights',location:'Dhanmondi, Dhaka',type:'Apartment',status:'For Sale',price:520000,beds:3,rooms:5,baths:3,size:'1,950 Sq Ft',img:'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=85',description:'A bright apartment close to Dhanmondi amenities.',amenities:'Lift, Parking, Security'},
{id:6,title:'The Garden Retreat',location:'Uttara, Dhaka',type:'Home',status:'For Rent',price:1800,beds:4,rooms:7,baths:3,size:'2,800 Sq Ft',img:'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=900&q=85',description:'A comfortable home with generous rooms and a peaceful setting.',amenities:'Parking, Garden, Security'}
];
const defaultBot={name:'Property Assistant',placeholder:'বাংলা / Banglish / English-এ লিখুন...',startup:'Hi! বাংলা, Banglish বা English-এ প্রশ্ন করুন। আমি property, price, rent, rooms ও location নিয়ে help করতে পারি.',quick:[{label:'Buy',message:'Buy'},{label:'Rent',message:'Rent'},{label:'Price',message:'Price'},{label:'Contact',message:'যোগাযোগ চাই'}],faqs:[]};
function clone(v){return JSON.parse(JSON.stringify(v))}
function getProperties(){try{const v=JSON.parse(localStorage.getItem(PROP_KEY)||'null');if(Array.isArray(v)&&v.length)return v}catch(e){}return clone(defaultProperties)}
function getBotSettings(){try{return {...clone(defaultBot),...JSON.parse(localStorage.getItem(BOT_KEY)||'{}')}}catch(e){return clone(defaultBot)}}
function money(n){return n>=1000000?'$'+(n/1000000).toFixed(2)+'M':n>=1000?'$'+n.toLocaleString():'$'+n.toLocaleString()+' / month'}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function card(p){return `<article class="card"><a href="property.html?id=${encodeURIComponent(p.id)}"><div class="card-img"><img src="${escapeHtml(p.img)}" alt="${escapeHtml(p.title)}" loading="lazy"><div class="badges"><span class="badge">${escapeHtml(p.status)}</span></div><button class="heart" aria-label="Save ${escapeHtml(p.title)}" onclick="event.preventDefault();toggleSave(${Number(p.id)})">♡</button></div><div class="card-body"><div class="location">⌖ ${escapeHtml(p.location)}</div><h3>${escapeHtml(p.title)}</h3><div class="meta"><span>▦ ${Number(p.beds)||0} Beds</span><span>♨ ${Number(p.baths)||0} Baths</span><span>▤ ${escapeHtml(p.size||'Size on request')}</span></div><div class="price">${money(Number(p.price)||0)}</div></div></a></article>`}
function renderFeatured(){const el=document.querySelector('[data-featured]');if(el)el.innerHTML=getProperties().slice(0,4).map(card).join('')}
function renderAll(){const el=document.querySelector('[data-properties]');if(!el)return;const q=(document.querySelector('#q')?.value||'').toLowerCase().trim();const type=document.querySelector('#type')?.value||'';const status=document.querySelector('#status')?.value||'';const list=getProperties().filter(p=>(!q||(p.title+' '+p.location+' '+p.type).toLowerCase().includes(q))&&(!type||p.type===type)&&(!status||p.status===status));el.innerHTML=list.length?list.map(card).join(''):'<div class="panel" style="grid-column:1/-1;text-align:center">No matching properties found.</div>'}
function toggleSave(id){const s=JSON.parse(localStorage.getItem('saved')||'[]');const next=s.includes(id)?s.filter(x=>x!==id):[...s,id];localStorage.setItem('saved',JSON.stringify(next))}
function bindNav(){const nav=document.querySelector('.nav');document.querySelector('.menu')?.addEventListener('click',()=>nav?.classList.toggle('mobile-open'))}
function bindSearch(){document.querySelector('#searchForm')?.addEventListener('submit',e=>{e.preventDefault();location.href='properties.html?q='+encodeURIComponent(document.querySelector('#searchQ')?.value||'')})}
function bindContact(){document.querySelectorAll('form[data-contact]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const note=f.querySelector('.form-note');if(note)note.textContent='Thanks — your request has been received. Our property advisor will contact you shortly.'}))}
function bindLogin(){document.querySelector('#loginBtn')?.addEventListener('click',()=>document.querySelector('#loginModal')?.classList.add('open'));document.querySelector('.close')?.addEventListener('click',()=>document.querySelector('#loginModal')?.classList.remove('open'));document.querySelector('#loginModal')?.addEventListener('click',e=>{if(e.target.id==='loginModal')e.currentTarget.classList.remove('open')});document.querySelector('#loginForm')?.addEventListener('submit',e=>{e.preventDefault();const email=e.currentTarget.querySelector('input[type="email"]')?.value||'';localStorage.setItem('borshaLogin',JSON.stringify({email,loggedIn:true}));alert('Demo login successful.');document.querySelector('#loginModal')?.classList.remove('open')})}
function initProperty(){const id=Number(new URLSearchParams(location.search).get('id'))||1;const p=getProperties().find(x=>Number(x.id)===id)||getProperties()[0];if(!p)return;document.querySelector('[data-title]')&&(document.querySelector('[data-title]').textContent=p.title);document.querySelector('[data-location]')&&(document.querySelector('[data-location]').textContent=p.location);document.querySelector('[data-price]')&&(document.querySelector('[data-price]').textContent=money(Number(p.price)||0));const img=document.querySelector('[data-main-img]');if(img)img.src=p.img;const meta=document.querySelector('[data-meta]');if(meta)meta.innerHTML=`<span>▦ ${Number(p.beds)||0} Beds</span><span>⌂ ${Number(p.rooms)||0} Rooms</span><span>♨ ${Number(p.baths)||0} Baths</span><span>▤ ${escapeHtml(p.size||'Size on request')}</span>`;const desc=document.querySelector('[data-description]');if(desc)desc.textContent=p.description||'Property details are available on request.';const amenities=document.querySelector('[data-amenities]');if(amenities)amenities.innerHTML=(p.amenities||'').split(',').map(x=>x.trim()).filter(Boolean).map(x=>`<div class="amenity">✓ ${escapeHtml(x)}</div>`).join('');const title=document.querySelector('title');if(title)title.textContent=p.title+' — Borsha Web';document.querySelector('[data-inquiry]')?.addEventListener('submit',e=>{e.preventDefault();const note=e.currentTarget.querySelector('.form-note');if(note)note.textContent='Inquiry sent successfully.'})}
function chatbotLanguage(text){if(/[\u0980-\u09ff]/.test(text))return 'bn';if(/\b(kemon|kothay|koto|koita|koiti|ache|ase|nai|chai|lagbe|dam|bari|basha|flat|room|rooms|bed|beds|bath|rent|buy|price|location|jante|bolen|bolo|apni|amar|apnar|tomar|ekhane|dekhao|dekhaw|property|properties|agent|whatsapp|contact)\b/i.test(text))return 'bnlish';return 'en'}
function findProperty(q){const props=getProperties();const clean=q.toLowerCase();return props.find(p=>clean.includes(String(p.title).toLowerCase()))||props.find(p=>clean.includes(String(p.location).toLowerCase()))||props.find(p=>clean.includes(String(p.type).toLowerCase()))||null}
function propertyFacts(p,lang,q){const wantsBed=/bed|beds|bedroom|শোবার|বেড/.test(q);const wantsRoom=/room|rooms|কয়টা রুম|কয়টা রুম|রুম/.test(q);const wantsBath=/bath|bathroom|বাথ/.test(q);const wantsPrice=/price|cost|dam|দাম|মূল্য|কত টাকা|koto/.test(q);const wantsSize=/size|area|sq|স্কয়ার|আয়তন|আয়তন/.test(q);const facts=[];if(wantsBed)facts.push(`${p.beds} beds`);if(wantsRoom)facts.push(`${p.rooms} rooms`);if(wantsBath)facts.push(`${p.baths} baths`);if(wantsSize)facts.push(p.size||'size on request');if(wantsPrice)facts.push(money(Number(p.price)||0));if(!facts.length)facts.push(`${p.beds} beds, ${p.rooms} rooms, ${p.baths} baths, ${p.size||'size on request'}, ${money(Number(p.price)||0)}`);if(lang==='bn')return `${p.title}-এ ${facts.join(', ')} আছে। Location: ${p.location}.`;if(lang==='bnlish')return `${p.title}-e ${facts.join(', ')} ache. Location: ${p.location}.`;return `${p.title} has ${facts.join(', ')}. Location: ${p.location}.`}
function chatbotReply(text){const settings=getBotSettings();const q=text.toLowerCase();const lang=chatbotLanguage(text);const p=findProperty(q);const custom=(settings.faqs||[]).find(f=>f.question&&q.includes(f.question.toLowerCase()));if(custom)return custom.answer;if(p)return propertyFacts(p,lang,q);const props=getProperties();if(/list|show|property|properties|ki ki|কি কি|কোন কোন|কয়টা property|কয়টা property/.test(q)){const names=props.slice(0,8).map(x=>`${x.title} (${x.location})`).join('; ');if(lang==='bn')return `বর্তমানে ${props.length}টি property আছে: ${names}`;if(lang==='bnlish')return `Ekhon ${props.length}ti property ache: ${names}`;return `We currently have ${props.length} properties: ${names}.`}if(/rent|rental|bhara|vara|ভাড়া|ভাড়া/.test(q)){const r=props.filter(x=>x.status==='For Rent');if(lang==='bn')return r.length?`Rental property: ${r.map(x=>`${x.title} (${money(x.price)})`).join(', ')}`:'এখন কোনো rental property নেই।';if(lang==='bnlish')return r.length?`Rental property: ${r.map(x=>`${x.title} (${money(x.price)})`).join(', ')}`:'Ekhon kono rental property nei.';return r.length?`Rental properties: ${r.map(x=>`${x.title} (${money(x.price)})`).join(', ')}`:'There are no rental properties right now.'}if(/buy|sale|sell|কেনা|কিনবো|বিক্রি|বিক্রয়/.test(q)){const s=props.filter(x=>x.status==='For Sale');if(lang==='bn')return `Sale property: ${s.map(x=>`${x.title} (${money(x.price)})`).join(', ')}`;if(lang==='bnlish')return `Sale property: ${s.map(x=>`${x.title} (${money(x.price)})`).join(', ')}`;return `For-sale properties: ${s.map(x=>`${x.title} (${money(x.price)})`).join(', ')}`}if(/contact|call|whatsapp|যোগাযোগ|ফোন|এজেন্ট|হোয়াটসঅ্যাপ|হোয়াটসঅ্যাপ/.test(q)){if(lang==='bn')return 'Contact page থেকে যোগাযোগ করতে পারেন অথবা নিচের WhatsApp button ব্যবহার করুন।';if(lang==='bnlish')return 'Contact page theke jogajog korte paren othoba bottom-right WhatsApp button use korte paren.';return 'You can use the Contact page or the WhatsApp button at the bottom-right.'}if(lang==='bn')return settings.startup;if(lang==='bnlish')return settings.startup;return settings.startup}
function initChatbot(){if(document.querySelector('.chatbot-launcher'))return;const s=getBotSettings();const quick=(s.quick||[]).filter(x=>x.label&&x.message);const wrap=document.createElement('div');wrap.innerHTML=`<button class="chatbot-launcher" id="chatbotLauncher" aria-label="Open property assistant" title="${escapeHtml(s.name)}"><span>✦</span></button><section class="chatbot-panel" id="chatbotPanel" aria-label="${escapeHtml(s.name)}"><div class="chatbot-head"><div><strong>${escapeHtml(s.name)}</strong><small>বাংলা · Banglish · English</small></div><button id="chatbotClose" aria-label="Close chatbot">×</button></div><div class="chatbot-messages" id="chatbotMessages"><div class="chat-msg bot"></div></div><div class="chatbot-quick">${quick.map(x=>`<button data-chat="${escapeHtml(x.message)}">${escapeHtml(x.label)}</button>`).join('')}</div><form class="chatbot-form" id="chatbotForm"><input id="chatbotInput" autocomplete="off" placeholder="${escapeHtml(s.placeholder)}"><button aria-label="Send message">➜</button></form></section>`;document.body.appendChild(wrap);const panel=document.querySelector('#chatbotPanel'),messages=document.querySelector('#chatbotMessages'),input=document.querySelector('#chatbotInput');messages.querySelector('.bot').textContent=s.startup;const add=(text,who='bot')=>{const d=document.createElement('div');d.className=`chat-msg ${who}`;d.textContent=text;messages.appendChild(d);messages.scrollTop=messages.scrollHeight};document.querySelector('#chatbotLauncher').addEventListener('click',()=>{panel.classList.toggle('open');if(panel.classList.contains('open'))input.focus()});document.querySelector('#chatbotClose').addEventListener('click',()=>panel.classList.remove('open'));document.querySelectorAll('[data-chat]').forEach(b=>b.addEventListener('click',()=>{const text=b.dataset.chat;add(text,'user');setTimeout(()=>add(chatbotReply(text)),120)}));document.querySelector('#chatbotForm').addEventListener('submit',e=>{e.preventDefault();const text=input.value.trim();if(!text)return;add(text,'user');input.value='';setTimeout(()=>add(chatbotReply(text)),120)})}
document.addEventListener('DOMContentLoaded',()=>{bindNav();bindSearch();bindContact();bindLogin();renderFeatured();renderAll();if(document.querySelector('[data-title]'))initProperty();const params=new URLSearchParams(location.search);if(params.get('q')&&document.querySelector('#q')){document.querySelector('#q').value=params.get('q');renderAll()}initChatbot()});