const properties=[
{id:1,title:'Azure Hills Villa',location:'Gulshan, Dhaka',type:'Villa',status:'For Sale',price:1250000,bed:5,bath:5,size:'4,500 Sq Ft',img:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=85'},
{id:2,title:'Skyline Residence',location:'Banani, Dhaka',type:'Apartment',status:'For Sale',price:680000,bed:3,bath:3,size:'2,200 Sq Ft',img:'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=900&q=85'},
{id:3,title:'Warmwood Family Home',location:'Bashundhara, Dhaka',type:'Home',status:'For Rent',price:2500,bed:4,bath:4,size:'3,200 Sq Ft',img:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=85'},
{id:4,title:'Palm Court Estate',location:'Mohammadpur, Dhaka',type:'Villa',status:'For Sale',price:950000,bed:4,bath:4,size:'3,000 Sq Ft',img:'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=900&q=85'},
{id:5,title:'Lakeview Heights',location:'Dhanmondi, Dhaka',type:'Apartment',status:'For Sale',price:520000,bed:3,bath:3,size:'1,950 Sq Ft',img:'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=85'},
{id:6,title:'The Garden Retreat',location:'Uttara, Dhaka',type:'Home',status:'For Rent',price:1800,bed:4,bath:3,size:'2,800 Sq Ft',img:'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=900&q=85'}
];
function money(n){return n>=1000000?'$'+(n/1000000).toFixed(2)+'M':n>=1000?'$'+n.toLocaleString():'$'+n.toLocaleString()+' / month'}
function card(p){return `<article class="card"><a href="property.html?id=${p.id}"><div class="card-img"><img src="${p.img}" alt="${p.title}" loading="lazy"><div class="badges"><span class="badge">${p.status}</span>${p.id===4?'<span class="badge gold">Hot Deal</span>':''}</div><button class="heart" aria-label="Save ${p.title}" onclick="event.preventDefault();toggleSave(${p.id})">♡</button></div><div class="card-body"><div class="location">⌖ ${p.location}</div><h3>${p.title}</h3><div class="meta"><span>▦ ${p.bed} Beds</span><span>♨ ${p.bath} Baths</span><span>▤ ${p.size}</span></div><div class="price">${money(p.price)}</div></div></a></article>`}
function renderFeatured(){const el=document.querySelector('[data-featured]');if(el)el.innerHTML=properties.slice(0,4).map(card).join('')}
function renderAll(){const el=document.querySelector('[data-properties]');if(!el)return;const q=(document.querySelector('#q')?.value||'').toLowerCase();const type=document.querySelector('#type')?.value||'';const status=document.querySelector('#status')?.value||'';const list=properties.filter(p=>(!q||(p.title+p.location).toLowerCase().includes(q))&&(!type||p.type===type)&&(!status||p.status===status));el.innerHTML=list.length?list.map(card).join(''):'<div class="panel" style="grid-column:1/-1;text-align:center">No matching properties found.</div>'}
function toggleSave(id){const s=JSON.parse(localStorage.getItem('saved')||'[]');const next=s.includes(id)?s.filter(x=>x!==id):[...s,id];localStorage.setItem('saved',JSON.stringify(next));}
function bindNav(){const nav=document.querySelector('.nav');document.querySelector('.menu')?.addEventListener('click',()=>nav.classList.toggle('mobile-open'));}
function bindSearch(){document.querySelector('#searchForm')?.addEventListener('submit',e=>{e.preventDefault();location.href='properties.html?q='+encodeURIComponent(document.querySelector('#searchQ')?.value||'')})}
function bindContact(){document.querySelectorAll('form[data-contact]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const note=f.querySelector('.form-note');if(note){note.textContent='Thanks — your request has been received. Our property advisor will contact you shortly.';note.style.color='#1e9a63'}}))}
function bindLogin(){document.querySelector('#loginBtn')?.addEventListener('click',()=>document.querySelector('#loginModal')?.classList.add('open'));document.querySelector('.close')?.addEventListener('click',()=>document.querySelector('#loginModal')?.classList.remove('open'));document.querySelector('#loginModal')?.addEventListener('click',e=>{if(e.target.id==='loginModal')e.currentTarget.classList.remove('open')});document.querySelector('#loginForm')?.addEventListener('submit',e=>{e.preventDefault();const email=e.currentTarget.querySelector('input[type="email"]')?.value||'';localStorage.setItem('borshaLogin',JSON.stringify({email,loggedIn:true}));alert('Demo login successful.');document.querySelector('#loginModal')?.classList.remove('open');})}
function initProperty(){const id=Number(new URLSearchParams(location.search).get('id'))||1;const p=properties.find(x=>x.id===id)||properties[0];document.querySelector('[data-title]').textContent=p.title;document.querySelector('[data-location]').textContent=p.location;document.querySelector('[data-price]').textContent=money(p.price);document.querySelector('[data-main-img]').src=p.img;document.querySelector('[data-meta]').innerHTML=`<span>▦ ${p.bed} Beds</span><span>♨ ${p.bath} Baths</span><span>▤ ${p.size}</span>`;document.querySelector('[data-inquiry]')?.addEventListener('submit',e=>{e.preventDefault();document.querySelector('.form-note').textContent='Inquiry sent successfully.'})}
function chatbotReply(text){const q=text.toLowerCase();if(/price|cost|budget/.test(q))return 'Our featured properties start around $520K for sale, while rental options start around $1,800/month. Tell me your budget and I can narrow the options.';if(/rent|rental/.test(q))return 'We currently have rental options in Bashundhara and Uttara. Open Properties and choose “For Rent” to browse them.';if(/buy|sale|sell/.test(q))return 'For-sale listings include villas and apartments in Gulshan, Banani, Mohammadpur and Dhanmondi.';if(/location|where|gulshan|banani|dhaka|uttara|bashundhara|dhanmondi/.test(q))return 'We currently feature properties across Gulshan, Banani, Bashundhara, Mohammadpur, Dhanmondi and Uttara.';if(/contact|call|whatsapp|agent/.test(q))return 'You can contact us from the Contact page or use the WhatsApp button at the bottom-right of the website.';if(/property|home|house|apartment|villa/.test(q))return 'I can help you explore apartments, villas and homes. Try asking about buying, renting, price or location.';return 'Hi! I can help you find properties, check prices, locations, rentals and contact options. What would you like to know?'}
function initChatbot(){if(document.querySelector('.chatbot-launcher'))return;const wrap=document.createElement('div');wrap.innerHTML=`<button class="chatbot-launcher" id="chatbotLauncher" aria-label="Open property assistant" title="Property Assistant"><span>✦</span></button><section class="chatbot-panel" id="chatbotPanel" aria-label="Property Assistant"><div class="chatbot-head"><div><strong>Property Assistant</strong><small>Ask about homes & listings</small></div><button id="chatbotClose" aria-label="Close chatbot">×</button></div><div class="chatbot-messages" id="chatbotMessages"><div class="chat-msg bot">Hi! I can help with properties, prices, rentals and locations.</div></div><div class="chatbot-quick"><button data-chat="Buy">Buy</button><button data-chat="Rent">Rent</button><button data-chat="Price">Price</button><button data-chat="Contact">Contact</button></div><form class="chatbot-form" id="chatbotForm"><input id="chatbotInput" autocomplete="off" placeholder="Ask about a property..."><button aria-label="Send message">➜</button></form></section>`;document.body.appendChild(wrap);const panel=document.querySelector('#chatbotPanel'),messages=document.querySelector('#chatbotMessages'),input=document.querySelector('#chatbotInput');const add=(text,who='bot')=>{const d=document.createElement('div');d.className=`chat-msg ${who}`;d.textContent=text;messages.appendChild(d);messages.scrollTop=messages.scrollHeight};document.querySelector('#chatbotLauncher').addEventListener('click',()=>{panel.classList.toggle('open');if(panel.classList.contains('open'))input.focus()});document.querySelector('#chatbotClose').addEventListener('click',()=>panel.classList.remove('open'));document.querySelectorAll('[data-chat]').forEach(b=>b.addEventListener('click',()=>{const text=b.dataset.chat;add(text,'user');setTimeout(()=>add(chatbotReply(text)),180)}));document.querySelector('#chatbotForm').addEventListener('submit',e=>{e.preventDefault();const text=input.value.trim();if(!text)return;add(text,'user');input.value='';setTimeout(()=>add(chatbotReply(text)),180)})}
document.addEventListener('DOMContentLoaded',()=>{bindNav();bindSearch();bindContact();bindLogin();renderFeatured();renderAll();if(document.querySelector('[data-title]'))initProperty();const params=new URLSearchParams(location.search);if(params.get('q')&&document.querySelector('#q')){document.querySelector('#q').value=params.get('q');renderAll()}initChatbot();});