const http=require("http");const fs=require("fs");const path=require("path");const crypto=require("crypto");
const PORT=Number(process.env.PORT||10000),ROOT=__dirname,DATA=path.join(ROOT,"data","site.json"),PUBLIC=path.join(ROOT,"public"),sessions=new Map();
function readData(){return JSON.parse(fs.readFileSync(DATA,"utf8"))} function writeData(d){fs.writeFileSync(DATA,JSON.stringify(d,null,2))}
function json(res,s,p){const b=JSON.stringify(p);res.writeHead(s,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});res.end(b)}
function body(req){return new Promise((ok,bad)=>{let r="";req.on("data",c=>{r+=c;if(r.length>1e6)req.destroy()});req.on("end",()=>{try{ok(r?JSON.parse(r):{})}catch(e){bad(e)}});req.on("error",bad)})}
function auth(req){const t=(req.headers.authorization||"").replace(/^Bearer\s+/,"");return t&&sessions.has(t)}
function safeFile(u){const c=decodeURIComponent((u||"/").split("?")[0]),q=c==="/"?"/index.html":c,f=path.normalize(path.join(PUBLIC,q));return f.startsWith(PUBLIC+path.sep)?f:null}
const types={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json; charset=utf-8",".jpg":"image/jpeg",".jpeg":"image/jpeg",".png":"image/png",".svg":"image/svg+xml",".webp":"image/webp"};
http.createServer(async(req,res)=>{try{
if(req.url==="/api/site"&&req.method==="GET")return json(res,200,readData());
if(req.url==="/api/products"&&req.method==="GET")return json(res,200,readData().products);
if(req.url==="/api/login"&&req.method==="POST"){const b=await body(req);if(b.username!==(process.env.ADMIN_USER||"admin")||b.password!==(process.env.ADMIN_PASSWORD||"change-me"))return json(res,401,{error:"Invalid credentials"});const t=crypto.randomBytes(24).toString("hex");sessions.set(t,Date.now());return json(res,200,{token:t})}
if(req.url==="/api/orders"&&req.method==="POST"){const b=await body(req);if(!b.items?.length)return json(res,400,{error:"Cart is empty"});return json(res,201,{orderId:"NXT-"+String(Date.now()).slice(-8),status:"Pending",message:"Order received"})}
if(req.url==="/api/admin/products"&&req.method==="POST"){if(!auth(req))return json(res,401,{error:"Unauthorized"});const b=await body(req),d=readData();if(!b.name||!b.category||!Number.isFinite(Number(b.price)))return json(res,400,{error:"name, category and numeric price are required"});const p={id:"NT-"+Date.now().toString().slice(-8),name:String(b.name),category:String(b.category),brand:String(b.brand||"NEXORA"),price:Number(b.price),oldPrice:Number(b.oldPrice||b.price),stock:Number(b.stock||0),rating:Number(b.rating||5),badge:String(b.badge||"New"),image:String(b.image||"")};d.products.push(p);writeData(d);return json(res,201,p)}
if(req.url==="/api/chat"&&req.method==="POST"){const b=await body(req),q=String(b.message||"").toLowerCase(),d=readData();let reply="I’m NEXORA Tech Assistant. Ask about products, PC builds, price, stock or orders.";if(/gaming pc|gaming computer|pc build|computer|pc/.test(q)){const p=d.products.find(x=>x.category==="Desktop PC");reply=`Gaming PC: ${p.name} — ৳${p.price.toLocaleString("en-BD")}. Stock: ${p.stock}. Tell me your budget for a compatible build.`}else if(/laptop/.test(q)){const p=d.products.find(x=>x.category==="Laptop");reply=`${p.name} — ৳${p.price.toLocaleString("en-BD")}. Tell me your budget and use case.`}else{const hits=d.products.filter(p=>q.includes(p.category.toLowerCase())||q.includes(p.name.toLowerCase())).slice(0,3);if(hits.length)reply=hits.map(p=>`${p.name} — ৳${p.price.toLocaleString("en-BD")}`).join(" | ")}return json(res,200,{reply})}
const f=safeFile(req.url);if(!f)return res.writeHead(403).end("Forbidden");fs.stat(f,(e,st)=>{if(e||!st.isFile())return res.writeHead(404).end("Not Found");res.writeHead(200,{"Content-Type":types[path.extname(f).toLowerCase()]||"application/octet-stream"});fs.createReadStream(f).pipe(res)})}
catch(e){json(res,500,{error:"Server error"})}}).listen(PORT,"0.0.0.0",()=>console.log(`NEXORA TECH running on ${PORT}`));