const http=require("http");
const fs=require("fs");
const path=require("path");
const crypto=require("crypto");
const PORT=Number(process.env.PORT||10000);
const ROOT=__dirname;
const DATA_DIR=path.join(ROOT,"data");
const DATA_FILE=path.join(DATA_DIR,"site.json");
const PUBLIC=path.join(ROOT,"public");
const sessionsSecret=process.env.SESSION_SECRET||crypto.randomBytes(32).toString("hex");
const rateBuckets=new Map();
const TYPES={".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json; charset=utf-8",".jpg":"image/jpeg",".jpeg":"image/jpeg",".png":"image/png",".webp":"image/webp",".gif":"image/gif",".svg":"image/svg+xml",".ico":"image/x-icon"};

function ensureData(){if(!fs.existsSync(DATA_DIR))fs.mkdirSync(DATA_DIR,{recursive:true});}
function readData(){ensureData();if(!fs.existsSync(DATA_FILE))fs.writeFileSync(DATA_FILE,JSON.stringify(seedData(),null,2));return JSON.parse(fs.readFileSync(DATA_FILE,"utf8"))}
function writeData(data){ensureData();const tmp=DATA_FILE+".tmp";fs.writeFileSync(tmp,JSON.stringify(data,null,2));fs.renameSync(tmp,DATA_FILE)}
function now(){return new Date().toISOString()}
function uid(prefix){return prefix+"-"+crypto.randomBytes(4).toString("hex")}
function text(v,max){return String(v==null?"":v).trim().slice(0,max)}
function number(v,fallback=0){const n=Number(v);return Number.isFinite(n)?n:fallback}
function safeImage(v){const s=String(v||"").trim();if(!s)return "";if(s.length>1800000)throw new Error("Image is too large. Use an optimized image.");if(/^data:image\/(png|jpeg|jpg|webp|gif);base64,/i.test(s))return s;if(/^https?:\/\/[^\s]+$/i.test(s))return s.slice(0,1800);throw new Error("Image must be an https URL or image upload.")}
function isEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||""))}
function json(res,status,payload,headers){res.writeHead(status,Object.assign({"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"},headers||{}));res.end(JSON.stringify(payload))}
function html(res,status,body,headers){res.writeHead(status,Object.assign({"Content-Type":"text/html; charset=utf-8","X-Content-Type-Options":"nosniff","Referrer-Policy":"strict-origin-when-cross-origin","Permissions-Policy":"camera=(), microphone=(), geolocation=()","Content-Security-Policy":"default-src 'self' https://images.unsplash.com https://wa.me https://m.me; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self'; frame-ancestors 'self'","Cache-Control":"no-store"},headers||{}));res.end(body)}
function parseBody(req,limit=2200000){return new Promise((resolve,reject)=>{let raw="";req.on("data",chunk=>{raw+=chunk;if(raw.length>limit){reject(new Error("Payload too large"));req.destroy()}});req.on("end",()=>{try{resolve(raw?JSON.parse(raw):{})}catch(e){reject(new Error("Invalid JSON"))}});req.on("error",reject)})}
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function sign(value){return crypto.createHmac("sha256",sessionsSecret).update(value).digest("hex")}
function makeSession(user){const payload=Buffer.from(JSON.stringify({u:user,exp:Date.now()+8*60*60*1000})).toString("base64url");return payload+"."+sign(payload)}
function sessionUser(req){const c=String(req.headers.cookie||"").split(";").map(x=>x.trim()).find(x=>x.startsWith("nx_admin="));if(!c)return null;const parts=c.slice(9).split(".");if(parts.length!==2||sign(parts[0])!==parts[1])return null;try{const d=JSON.parse(Buffer.from(parts[0],"base64url").toString("utf8"));return d.exp>Date.now()?d.u:null}catch{return null}}
function passwordOk(password){const hash=process.env.ADMIN_PASSWORD_HASH;if(hash&&hash.includes("$")){const p=hash.split("$");if(p.length!==2)return false;const d=crypto.scryptSync(password,p[0],64).toString("hex");return crypto.timingSafeEqual(Buffer.from(d,"hex"),Buffer.from(p[1],"hex"))}const configured=process.env.ADMIN_PASSWORD;if(!configured)return false;const a=Buffer.from(String(password)),b=Buffer.from(String(configured));return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function originOk(req){const origin=req.headers.origin;if(!origin)return true;try{return new URL(origin).host===req.headers.host}catch{return false}}
function rateLimited(req,scope){const key=(req.headers["x-forwarded-for"]||req.socket.remoteAddress||"unknown")+"|"+scope,n=Date.now(),row=rateBuckets.get(key)||{start:n,count:0};if(n-row.start>60000){row.start=n;row.count=0}row.count++;rateBuckets.set(key,row);return row.count>60}
function requireAdmin(req,res){if(!sessionUser(req)){json(res,401,{error:"Unauthorized"});return false}if(!originOk(req)){json(res,403,{error:"Invalid request origin"});return false}return true}

function socialIcon(k){return ({facebook:"f",instagram:"◎",tiktok:"♪",youtube:"▶",whatsapp:"◉"})[k]||"•"}
function pageShell(meta,content,active){
  const d=readData(),s=d.settings;
  const nav=[["Home","/"],["Shop","/shop"],["Services","/services"],["Packages","/packages"],["Portfolio","/portfolio"],["Reviews","/reviews"],["Contact","/contact"]];
  const social=Object.keys(s.socials||{}).map(k=>"<a class='social' href='"+esc(s.socials[k]||"#")+"' aria-label='"+esc(k)+"' target='_blank' rel='noopener'>"+socialIcon(k)+"</a>").join("");
  return "<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>"+esc(meta.title)+"</title><meta name='description' content='"+esc(meta.description)+"'><meta name='theme-color' content='#6256ff'><meta property='og:title' content='"+esc(meta.title)+"'><meta property='og:description' content='"+esc(meta.description)+"'><link rel='canonical' href='"+esc(meta.canonical||"/")+"'><link rel='stylesheet' href='/style.css'></head><body>"+
  "<div class='announce'><span>"+esc(s.maker)+"</span><span class='announceHide'>•</span><span>"+esc(s.sponsor)+"</span></div>"+
  "<header class='siteHeader'><div class='wrap navWrap'><a class='brand' href='/'><span class='brandLogo'>N</span><span><b>NEXORA</b><em>TECH</em></span></a><button class='menuBtn' id='menuBtn' aria-label='Open menu' aria-expanded='false'>☰</button><nav class='nav' id='nav'>"+nav.map(x=>"<a class='"+(active===x[1]?"active":"")+"' href='"+x[1]+"'>"+x[0]+"</a>").join("")+"</nav><div class='headerTools'><a class='iconBtn wa' href='https://wa.me/"+esc(s.whatsapp)+"' target='_blank' rel='noopener' aria-label='WhatsApp'>◉</a><div class='searchBox'><input id='globalSearch' placeholder='Search products, services...'><a href='/search' aria-label='Search'>⌕</a></div><a class='cartBtn' href='/cart' aria-label='Cart'>🛒<span id='cartCount'>0</span></a><a class='navCta' href='/contact'>"+esc(s.ctaText)+" ↗</a></div></div></header>"+
  "<main>"+content+"</main>"+
  "<footer class='footer'><div class='wrap footerGrid'><div><div class='brand footerBrand'><span class='brandLogo'>N</span><span><b>NEXORA</b><em>TECH</em></span></div><p>"+esc(s.tagline)+"</p><div class='makerBlock'><strong>"+esc(s.maker)+"</strong><small>"+esc(s.sponsor)+"</small></div></div><div><h4>Explore</h4><a href='/shop'>Shop</a><a href='/services'>Services</a><a href='/packages'>Packages</a><a href='/portfolio'>Portfolio</a></div><div><h4>Company</h4><a href='/about'>About</a><a href='/reviews'>Reviews</a><a href='/contact'>Contact</a><a href='/admin'>Admin</a></div><div><h4>Contact</h4><a href='tel:"+esc(s.phone)+"'>"+esc(s.phone)+"</a><a href='mailto:"+esc(s.email)+"'>"+esc(s.email)+"</a><span>"+esc(s.address)+"</span><div class='socialRow'>"+social+"</div></div></div><div class='wrap footerBottom'><span>© 2026 "+esc(s.brand)+". All rights reserved.</span><span><a href='/privacy'>Privacy</a> · <a href='/terms'>Terms</a></span></div></footer>"+
  "<div class='agent' id='agent'><button class='agentBtn' id='agentBtn' aria-label='Contact agent'>⌁</button><div class='agentMenu' id='agentMenu'><a href='tel:"+esc(s.phone)+"'>☎ Call</a><a href='https://wa.me/"+esc(s.whatsapp)+"' target='_blank' rel='noopener'>◉ WhatsApp</a><a href='"+esc(s.messenger)+"' target='_blank' rel='noopener'>◌ Messenger</a></div></div>"+
  "<div class='chat' id='chat'><div class='chatHead'><b>NEXORA AI</b><button id='closeChat' aria-label='Close chat'>×</button></div><div class='chatBody' id='chatBody'><div class='msg ai'>Hi! Ask me about products, packages, PC builds or how to order. বাংলা / Banglish / English supported.</div></div><form id='chatForm'><input id='chatInput' placeholder='Ask NEXORA AI...'><button>➤</button></form></div><button class='chatFab' id='chatFab' aria-label='Open AI assistant'>✦</button>"+
  "<script src='/app.js' defer></script></body></html>";
}
function productCard(p){return "<article class='productCard'><a class='productImage' href='/product/"+esc(p.id)+"'><span class='badge'>"+esc(p.badge||"Featured")+"</span><img src='"+esc(p.image)+"' alt='"+esc(p.name)+"' loading='lazy'></a><div class='productBody'><div class='muted'>"+esc(p.brand)+" · "+esc(p.category)+"</div><h3><a href='/product/"+esc(p.id)+"'>"+esc(p.name)+"</a></h3><div class='rating'>★★★★★ <span>"+esc(p.rating)+"</span></div><div class='price'>৳"+Number(p.price||0).toLocaleString("en-BD")+" <del>৳"+Number(p.oldPrice||p.price||0).toLocaleString("en-BD")+"</del></div><div class='cardActions'><button class='smallBtn primaryBtn' data-add='"+esc(p.id)+"'>Add to cart</button><button class='smallBtn' data-compare='"+esc(p.id)+"'>Compare</button></div></div></article>"}
function renderHome(){
  const d=readData(),icons=["◫","▣","◈","▤","◉","⌘","✦","▥"];
  const cats=d.categories.slice(0,8).map((c,i)=>"<a class='catCard' href='/shop?category="+encodeURIComponent(c)+"'><span>"+icons[i%icons.length]+"</span><b>"+esc(c)+"</b><small>Explore</small></a>").join("");
  const featured=d.products.slice(0,4).map(productCard).join("");
  const services=d.services.map(x=>"<article class='featureCard'><div class='serviceIcon'>"+esc(x.icon)+"</div><div><div class='eyebrow'>SERVICE</div><h3>"+esc(x.title)+"</h3><p>"+esc(x.description)+"</p><ul>"+x.features.slice(0,4).map(f=>"<li>✓ "+esc(f)+"</li>").join("")+"</ul><a href='/services#"+esc(x.id)+"'>Explore service ↗</a></div></article>").join("");
  const packages=d.packages.filter(x=>x.visibility).map(x=>"<article class='packageCard "+(x.featured?"featured":"")+"'><div class='packageTop'><span>"+(x.featured?"MOST REQUESTED":"PACKAGE")+"</span></div><h3>"+esc(x.name)+"</h3><div class='packagePrice'>৳"+Number(x.price).toLocaleString("en-BD")+" <small>"+esc(x.period)+"</small></div><ul>"+x.features.slice(0,7).map(f=>"<li>✓ "+esc(f)+"</li>").join("")+"</ul><a class='btn "+(x.featured?"primary":"ghost")+"' href='/contact?package="+encodeURIComponent(x.name)+"'>Choose package ↗</a></article>").join("");
  const portfolio=d.portfolio.map(x=>"<a class='portfolioCard' href='/portfolio#"+esc(x.id)+"'><img src='"+esc(x.image)+"' alt='"+esc(x.title)+"' loading='lazy'><div><span>"+esc(x.category)+"</span><h3>"+esc(x.title)+"</h3><p>"+esc(x.description)+"</p></div></a>").join("");
  const reviews=[...d.reviews,...d.reviews].map(x=>"<article class='reviewCard'><div class='reviewHead'><img src='"+esc(x.image)+"' alt='' loading='lazy'><div><b>"+esc(x.name)+"</b><span>"+esc(x.date)+"</span></div><strong>★★★★★</strong></div><p>“"+esc(x.text)+"”</p></article>").join("");
  const faq=[["Which package should I choose?","Basic works for simple online presence, Business adds deeper conversion and editability, while Premium E-commerce is structured around online selling."],["Can I edit content later?","Yes. The architecture includes an admin-ready content layer so the public site does not have to be rebuilt for normal content updates."],["Do you integrate WhatsApp and social channels?","Yes. Contact, WhatsApp and social links are part of the standard experience."],["Is the store mobile friendly?","Yes. The site is designed mobile-first with touch-friendly controls and responsive sections."]].map(x=>"<details class='faq'><summary>"+esc(x[0])+" <span>+</span></summary><p>"+esc(x[1])+"</p></details>").join("");
  return "<section class='hero'><div class='wrap heroGrid'><div class='heroCopy'><div class='eyebrow'>NEXT-GEN TECHNOLOGY STORE</div><h1>"+esc(d.settings.heroTitle).replace("Go Beyond.","<span>Go Beyond.</span>")+"</h1><p>"+esc(d.settings.heroDescription)+"</p><div class='heroBtns'><a class='btn primary' href='/shop'>Explore Products ↗</a><a class='btn ghost' href='/builder'>Build Your PC</a></div><div class='heroTrust'><span>✓ Curated products</span><span>✓ Bangladesh-wide support</span><span>✓ Smart shopping assistant</span></div></div><div class='heroVisual'><div class='heroGlow'></div><div class='heroFrame'><img src='"+esc(d.settings.heroImage)+"' alt='Premium technology setup' loading='eager'></div><div class='floatingCard'><small>SMART RECOMMENDATION</small><strong>Tell us your budget.</strong><span>We help narrow down the right setup.</span></div></div></div></section>"+
  "<section class='trustStrip'><div>⚡ <b>Fast shopping</b><small>Clear routes from discovery to checkout.</small></div><div>🔒 <b>Secure flow</b><small>Protected admin and validated forms.</small></div><div>🛠 <b>Support ready</b><small>WhatsApp / call / messenger options.</small></div><div>✦ <b>NEXORA AI</b><small>Product and package guidance.</small></div></section>"+
  "<section class='section'><div class='wrap'><div class='sectionHead'><div><div class='eyebrow'>CURATED FOR YOU</div><h2>Shop by category.</h2></div><a href='/shop'>View all ↗</a></div><div class='categoryGrid'>"+cats+"</div></div></section>"+
  "<section class='section soft'><div class='wrap'><div class='sectionHead'><div><div class='eyebrow'>SMART SHOPPING</div><h2>Trending products.</h2></div><a href='/shop'>Browse store ↗</a></div><div class='productGrid'>"+featured+"</div></div></section>"+
  "<section class='section builderPreview'><div class='wrap twoCol'><div><div class='eyebrow'>NEXORA CONFIGURATOR</div><h2>Build your PC around a budget.</h2><p>Choose your range and get an immediate starter recommendation, then refine it with support.</p><a class='btn primary' href='/builder'>Open PC Builder ↗</a></div><div class='builderCard'><div class='builderKnob'>BDT</div><div><span>Suggested starting range</span><strong>৳80k — ৳150k</strong><small>Gaming · Creator · Productivity</small></div></div></div></section>"+
  "<section class='section'><div class='wrap'><div class='sectionHead'><div><div class='eyebrow'>WEB SERVICES</div><h2>Need a website too?</h2></div><a href='/services'>All services ↗</a></div><div class='serviceGrid'>"+services+"</div></div></section>"+
  "<section class='section soft'><div class='wrap'><div class='sectionHead'><div><div class='eyebrow'>PACKAGES</div><h2>Choose the right build.</h2></div><a href='/packages'>Compare packages ↗</a></div><div class='packageGrid'>"+packages+"</div></div></section>"+
  "<section class='section'><div class='wrap'><div class='sectionHead'><div><div class='eyebrow'>PORTFOLIO</div><h2>Made by Nexora Web.</h2></div><a href='/portfolio'>View portfolio ↗</a></div><div class='portfolioGrid'>"+portfolio+"</div></div></section>"+
  "<section class='section darkSection'><div class='wrap'><div class='sectionHead light'><div><div class='eyebrow'>CUSTOMER REVIEWS</div><h2>People talk about the details.</h2></div><a href='/reviews'>All reviews ↗</a></div><div class='reviewTrack'>"+reviews+"</div></div></section>"+
  "<section class='section'><div class='wrap faqWrap'><div><div class='eyebrow'>FAQ</div><h2>Clear answers before you buy.</h2></div><div>"+faq+"</div></div></section>"+
  "<section class='contactBanner'><div class='wrap contactBannerInner'><div><div class='eyebrow'>READY WHEN YOU ARE</div><h2>Build a better store or a better website.</h2><p>One team for product, e-commerce and web development.</p></div><a class='btn primary' href='/contact'>Talk to Nexora ↗</a></div></section>";
}
function renderShop(){const d=readData();return "<section class='pageHero'><div class='wrap'><div class='eyebrow'>NEXORA SHOP</div><h1>Technology without the noise.</h1><p>Search products, compare options and build a setup that fits the way you work.</p></div></section><section class='section'><div class='wrap'><div class='shopToolbar'><div class='chipRow'>"+d.categories.map(c=>"<a class='chip' href='/shop?category="+encodeURIComponent(c)+"'>"+esc(c)+"</a>").join("")+"</div><div class='shopFilters'><input id='shopSearch' placeholder='Search products...'><select id='categoryFilter'><option value=''>All categories</option>"+d.categories.map(c=>"<option>"+esc(c)+"</option>").join("")+"</select><select id='sort'><option value='featured'>Featured</option><option value='low'>Price: Low</option><option value='high'>Price: High</option></select></div></div><div id='shopProducts' class='productGrid'>"+d.products.map(productCard).join("")+"</div></div></section>"}
function renderServices(){const d=readData(),blocks=d.services.map(s=>"<article class='serviceDetail' id='"+esc(s.id)+"'><div class='serviceIcon'>"+esc(s.icon)+"</div><div><div class='eyebrow'>SERVICE</div><h2>"+esc(s.title)+"</h2><p>"+esc(s.description)+"</p><div class='featurePills'>"+s.features.map(f=>"<span>✓ "+esc(f)+"</span>").join("")+"</div><a class='btn primary' href='/contact?service="+encodeURIComponent(s.title)+"'>Request this service ↗</a></div></article>").join("");return "<section class='pageHero'><div class='wrap'><div class='eyebrow'>WEB SERVICES</div><h1>Design, development and growth in one connected system.</h1><p>From a simple business site to a custom commerce experience, choose the service layer that matches your goal.</p></div></section><section class='section'><div class='wrap serviceLong'>"+blocks+"</div></section>"}
function renderPackages(){const d=readData(),cards=d.packages.filter(x=>x.visibility).map(x=>"<article class='packageCard "+(x.featured?"featured":"")+"'><div class='packageTop'><span>"+(x.featured?"MOST REQUESTED":"PACKAGE")+"</span></div><h2>"+esc(x.name)+"</h2><p class='muted'>"+esc(x.period)+"</p><div class='packagePrice'>৳"+Number(x.price).toLocaleString("en-BD")+" <small>starting</small></div><ul>"+x.features.map(f=>"<li>✓ "+esc(f)+"</li>").join("")+"</ul><a class='btn "+(x.featured?"primary":"ghost")+"' href='/contact?package="+encodeURIComponent(x.name)+"'>Choose package ↗</a></article>").join("");return "<section class='pageHero'><div class='wrap'><div class='eyebrow'>PACKAGES</div><h1>Simple starting points. Flexible outcomes.</h1><p>Package scopes are starting points; the final build can be shaped around your content, integrations and timeline.</p></div></section><section class='section'><div class='wrap packageGrid'>"+cards+"</div></section><section class='section soft'><div class='wrap'><div class='compareTableWrap'><h2>Package comparison.</h2><div class='compareScroll'><table class='compareTable'><thead><tr><th>Feature</th><th>Basic</th><th>Business</th><th>Premium E-commerce</th></tr></thead><tbody><tr><td>Responsive design</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>WhatsApp integration</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>Advanced SEO</td><td>—</td><td>✓</td><td>✓</td></tr><tr><td>Admin / editable content</td><td>—</td><td>✓</td><td>✓</td></tr><tr><td>E-commerce</td><td>—</td><td>—</td><td>✓</td></tr><tr><td>Order management</td><td>—</td><td>—</td><td>✓</td></tr></tbody></table></div></div></div></section>"}
function renderPortfolio(){const d=readData(),cards=d.portfolio.map(x=>"<article class='portfolioCard portfolioDetail' id='"+esc(x.id)+"'><img src='"+esc(x.image)+"' alt='"+esc(x.title)+"' loading='lazy'><div class='portfolioInfo'><span>"+esc(x.category)+"</span><h2>"+esc(x.title)+"</h2><p>"+esc(x.description)+"</p><div class='featurePills'>"+x.technology.map(t=>"<span>"+esc(t)+"</span>").join("")+"</div><a class='btn primary' href='"+esc(x.url)+"' target='_blank' rel='noopener'>View website ↗</a></div></article>").join("");return "<section class='pageHero'><div class='wrap'><div class='eyebrow'>PORTFOLIO</div><h1>Websites and digital systems by Nexora Web.</h1><p>Explore project work across commerce, business websites and product interfaces.</p></div></section><section class='section'><div class='wrap portfolioList'>"+cards+"</div></section>"}
function renderReviews(){const d=readData(),cards=d.reviews.map(x=>"<article class='reviewBig'><img src='"+esc(x.image)+"' alt='' loading='lazy'><div><div class='rating'>★★★★★ <span>"+esc(x.rating)+"</span></div><p>“"+esc(x.text)+"”</p><strong>"+esc(x.name)+"</strong><small>"+esc(x.date)+"</small></div></article>").join("");return "<section class='pageHero'><div class='wrap'><div class='eyebrow'>REVIEWS</div><h1>What customers noticed.</h1><p>Compact reviews that help visitors understand the experience.</p></div></section><section class='section'><div class='wrap reviewGrid'>"+cards+"</div></section>"}
function renderAbout(){const s=readData().settings;return "<section class='pageHero'><div class='wrap'><div class='eyebrow'>ABOUT</div><h1>"+esc(s.brand)+" is built around useful technology and useful experiences.</h1><p>"+esc(s.tagline)+"</p></div></section><section class='section'><div class='wrap aboutGrid'><div><div class='eyebrow'>OUR STANDARD</div><h2>Premium should feel clear, fast and considered.</h2></div><div><p>We connect product presentation, e-commerce interaction and web development into one coherent system.</p><p>Every major interaction is designed to work with touch, keyboard and responsive layouts in mind.</p></div></div></section><section class='section soft'><div class='wrap metrics'><div><strong>12+</strong><span>Core product categories</span></div><div><strong>04</strong><span>Web service lines</span></div><div><strong>03</strong><span>Website packages</span></div><div><strong>24/7</strong><span>Digital presence</span></div></div></section>"}
function renderContact(){const s=readData().settings;return "<section class='pageHero'><div class='wrap'><div class='eyebrow'>CONTACT</div><h1>Tell us what you need to launch, sell or improve.</h1><p>Ask about a product, custom PC, website package or digital build.</p></div></section><section class='section'><div class='wrap contactGrid'><div><h2>Talk to NEXORA</h2><p>We can help with product questions, website planning, package selection and custom requirements.</p><div class='contactList'><a href='tel:"+esc(s.phone)+"'>☎ "+esc(s.phone)+"</a><a href='https://wa.me/"+esc(s.whatsapp)+"' target='_blank' rel='noopener'>◉ WhatsApp</a><a href='"+esc(s.messenger)+"' target='_blank' rel='noopener'>◌ Messenger</a><a href='mailto:"+esc(s.email)+"'>✉ "+esc(s.email)+"</a></div></div><form class='formCard' id='contactForm'><div class='formGrid'><label>Name<input name='name' required maxlength='80'></label><label>Email<input type='email' name='email' required maxlength='120'></label><label>Company<input name='company' maxlength='120'></label><label>Service<select name='service'><option>Website</option><option>Basic Website</option><option>Business Website</option><option>Premium E-commerce</option><option>Custom Development</option><option>Technology product</option></select></label><label class='full'>Message<textarea name='message' required maxlength='2500'></textarea></label></div><button class='btn primary' type='submit'>Send message ↗</button><div class='notice' id='contactNotice'></div></form></div></section>"}
function renderCart(){return "<section class='pageHero'><div class='wrap'><div class='eyebrow'>CART</div><h1>Your shopping list.</h1><p>Review quantities, remove items and continue to checkout.</p></div></section><section class='section'><div class='wrap cartLayout'><div id='cartPageItems' class='cartPageItems'></div><aside class='summaryCard'><div class='eyebrow'>ORDER SUMMARY</div><h2 id='cartPageTotal'>৳0</h2><a class='btn primary' href='/checkout'>Proceed to checkout ↗</a></aside></div></section>"}
function renderCheckout(){return "<section class='pageHero'><div class='wrap'><div class='eyebrow'>CHECKOUT</div><h1>Almost there.</h1><p>Enter delivery details and review your order before confirming.</p></div></section><section class='section'><div class='wrap checkoutGrid'><form class='formCard' id='checkoutForm'><div class='eyebrow'>CUSTOMER DETAILS</div><div class='formGrid'><label>Name<input name='name' required maxlength='80'></label><label>Phone<input name='phone' required maxlength='30'></label><label class='full'>Email<input type='email' name='email' maxlength='120'></label><label class='full'>Address<textarea name='address' required maxlength='500'></textarea></label></div><div class='eyebrow' style='margin-top:20px'>PAYMENT</div><label>Method<select name='payment'><option>Cash on delivery</option><option>Payment integration ready</option></select></label><button class='btn primary' style='margin-top:18px' type='submit'>Place order ↗</button><div class='notice' id='checkoutNotice'></div></form><aside class='summaryCard'><div class='eyebrow'>ORDER SUMMARY</div><div id='checkoutSummary'></div><h2 id='checkoutTotal'>৳0</h2></aside></div></section>"}
function renderSearch(){return "<section class='pageHero'><div class='wrap'><div class='eyebrow'>SEARCH</div><h1>Find the right place to start.</h1><p>Search across products, services and portfolio projects.</p><div class='bigSearch'><input id='searchPageInput' placeholder='Try gaming, website, e-commerce...'><button class='btn primary' id='searchPageBtn'>Search ↗</button></div></div></section><section class='section'><div class='wrap'><div id='searchResults' class='searchResults'></div></div></section>"}
function renderBuilder(){return "<section class='pageHero'><div class='wrap'><div class='eyebrow'>NEXORA CONFIGURATOR</div><h1>Build a starter PC around your budget.</h1><p>Choose a budget. We will generate a practical starting configuration using the catalog.</p></div></section><section class='section'><div class='wrap builderPage'><div class='formCard'><label>Budget in BDT<input id='builderBudget' type='number' min='10000' step='1000' placeholder='100000'></label><div class='builderRange'><button class='chip' data-budget='60000'>60k</button><button class='chip' data-budget='90000'>90k</button><button class='chip' data-budget='120000'>120k</button><button class='chip' data-budget='150000'>150k</button></div><button class='btn primary' id='generateBuild'>Generate Build ↗</button></div><div class='buildResult' id='buildResult'><div class='eyebrow'>YOUR RECOMMENDATION</div><h2>Start with a budget.</h2><p>Your suggested parts will appear here.</p></div></div></section>"}
function renderLegal(title){return "<section class='pageHero'><div class='wrap'><div class='eyebrow'>LEGAL</div><h1>"+esc(title)+"</h1><p>This page is a concise policy placeholder.</p></div></section><section class='section'><div class='wrap legalText'><h2>Overview</h2><p>Use of this website is subject to applicable laws, product terms and information shown at checkout.</p><h2>Information handling</h2><p>Contact and order forms are validated server-side. Admin data is protected behind authentication.</p></div></section>"}
function render404(){return "<section class='pageHero'><div class='wrap'><div class='eyebrow'>404</div><h1>That page is not here.</h1><p>The store is still right this way.</p><a class='btn primary' href='/'>Back home ↗</a></div></section>"}

function adminShell(){
 return "<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>NEXORA TECH Admin</title><meta name='robots' content='noindex,nofollow'><link rel='stylesheet' href='/style.css'></head><body class='adminBody'><div class='adminApp'><aside class='adminSide'><a class='brand' href='/'><span class='brandLogo'>N</span><span><b>NEXORA</b><em>ADMIN</em></span></a><nav><button data-view='dashboard' class='active'>Dashboard</button><button data-view='settings'>Website Settings</button><button data-view='services'>Services</button><button data-view='packages'>Packages</button><button data-view='products'>Products</button><button data-view='orders'>Orders</button><button data-view='reviews'>Reviews</button><button data-view='portfolio'>Portfolio</button><button data-view='contacts'>Contacts</button></nav><div class='adminSideBottom'><span>"+esc(readData().settings.maker)+"</span><a href='/'>Open store ↗</a></div></aside><main class='adminMain'><header class='adminTop'><div><div class='eyebrow'>CONTROL CENTER</div><h1 id='adminTitle'>Dashboard</h1></div><button class='btn ghost' id='adminLogout'>Sign out</button></header><div id='adminApp'></div></main></div><script src='/admin.js' defer></script></body></html>";
}
function pageFor(reqUrl){
 const u=new URL(reqUrl,"http://localhost"),p=u.pathname.replace(/\/+$/,"")||"/";
 if(p==="/admin")return {body:adminShell(),admin:true};
 const map={
 "/":{t:"NEXORA TECH — Premium Technology Store",d:"Premium technology commerce, web services and smart shopping.",c:"/",r:renderHome(),a:"/"},
 "/shop":{t:"Shop — NEXORA TECH",d:"Browse laptops, PCs, components, monitors, gaming and gadgets.",c:"/shop",r:renderShop(),a:"/shop"},
 "/services":{t:"Web Services — NEXORA WEB",d:"Basic websites, business websites, e-commerce and custom development.",c:"/services",r:renderServices(),a:"/services"},
 "/packages":{t:"Packages — NEXORA WEB",d:"Website package starting points for business and e-commerce.",c:"/packages",r:renderPackages(),a:"/packages"},
 "/portfolio":{t:"Portfolio — NEXORA WEB",d:"Selected websites and digital product work by Nexora Web.",c:"/portfolio",r:renderPortfolio(),a:"/portfolio"},
 "/reviews":{t:"Reviews — NEXORA TECH",d:"Customer reviews from the Nexora shopping experience.",c:"/reviews",r:renderReviews(),a:"/reviews"},
 "/about":{t:"About — NEXORA TECH",d:"About the Nexora Web standard and technology commerce experience.",c:"/about",r:renderAbout(),a:"/about"},
 "/contact":{t:"Contact — NEXORA TECH",d:"Talk to Nexora about products, websites and digital solutions.",c:"/contact",r:renderContact(),a:"/contact"},
 "/cart":{t:"Cart — NEXORA TECH",d:"Review your Nexora shopping cart.",c:"/cart",r:renderCart(),a:"/shop"},
 "/checkout":{t:"Checkout — NEXORA TECH",d:"Complete your Nexora order.",c:"/checkout",r:renderCheckout(),a:"/shop"},
 "/search":{t:"Search — NEXORA TECH",d:"Search products, services and portfolio.",c:"/search",r:renderSearch(),a:"/shop"},
 "/builder":{t:"PC Builder — NEXORA TECH",d:"Build a starter PC around your budget.",c:"/builder",r:renderBuilder(),a:"/shop"},
 "/privacy":{t:"Privacy — NEXORA TECH",d:"Privacy information.",c:"/privacy",r:renderLegal("Privacy"),a:""},
 "/terms":{t:"Terms — NEXORA TECH",d:"Terms and conditions.",c:"/terms",r:renderLegal("Terms & Conditions"),a:""}
 };
 if(map[p]){const m=map[p];return {body:pageShell({title:m.t,description:m.d,canonical:m.c},m.r,m.a)}}
 const m=p.match(/^\/product\/([^/]+)$/);
 if(m){const d=readData(),item=d.products.find(x=>x.id===m[1]);if(!item)return {body:pageShell({title:"Not found",description:"Product not found.",canonical:p},render404(),"")};const related=d.products.filter(x=>x.id!==item.id).slice(0,3).map(productCard).join(""),content="<section class='productHero'><div class='wrap productDetailGrid'><div class='detailImage'><img src='"+esc(item.image)+"' alt='"+esc(item.name)+"'></div><div><div class='eyebrow'>"+esc(item.brand)+" · "+esc(item.category)+"</div><h1>"+esc(item.name)+"</h1><div class='rating'>★★★★★ <span>"+esc(item.rating)+"</span></div><div class='detailPrice'>৳"+Number(item.price).toLocaleString("en-BD")+" <del>৳"+Number(item.oldPrice||item.price).toLocaleString("en-BD")+"</del></div><p>"+esc(item.description)+"</p><ul class='featureList'>"+item.features.map(f=>"<li>✓ "+esc(f)+"</li>").join("")+"</ul><div class='detailActions'><button class='btn primary' data-add='"+esc(item.id)+"'>Add to cart ↗</button><a class='btn ghost' href='/contact?product="+encodeURIComponent(item.name)+"'>Ask about this ↗</a></div><div class='stockNote'>"+(item.stock>0?"In stock · "+esc(item.stock)+" available":"Out of stock")+"</div></div></div></section><section class='section'><div class='wrap'><div class='sectionHead'><div><div class='eyebrow'>SPECIFICATIONS</div><h2>Details at a glance.</h2></div></div><div class='specGrid'>"+Object.keys(item.specs||{}).map(k=>"<div><span>"+esc(k)+"</span><strong>"+esc(item.specs[k])+"</strong></div>").join("")+"</div></div></section><section class='section soft'><div class='wrap'><div class='sectionHead'><div><div class='eyebrow'>YOU MAY ALSO LIKE</div><h2>More from the catalog.</h2></div></div><div class='productGrid'>"+related+"</div></div></section>";return {body:pageShell({title:item.name+" — NEXORA TECH",description:item.description,canonical:p},content,"/shop")}}
 return {body:pageShell({title:"404 — NEXORA TECH",description:"Page not found.",canonical:p},render404(),"")};
}

function norm(name,b){
 if(name==="products")return {id:text(b.id||uid("NT"),40),name:text(b.name,120),category:text(b.category,80),brand:text(b.brand||"NEXORA",80),price:number(b.price),oldPrice:number(b.oldPrice,b.price),stock:number(b.stock),rating:Math.min(5,Math.max(0,number(b.rating,5))),badge:text(b.badge||"New",40),image:safeImage(b.image||""),description:text(b.description,800),features:Array.isArray(b.features)?b.features.map(x=>text(x,120)).slice(0,12):String(b.features||"").split(",").map(x=>text(x,120)).filter(Boolean).slice(0,12),specs:typeof b.specs==="object"&&b.specs?b.specs:{}};
 if(name==="services")return {id:text(b.id||uid("svc"),40),icon:text(b.icon||"✦",8),title:text(b.title,120),description:text(b.description,700),features:Array.isArray(b.features)?b.features.map(x=>text(x,120)).slice(0,12):String(b.features||"").split(",").map(x=>text(x,120)).filter(Boolean).slice(0,12)};
 if(name==="packages")return {id:text(b.id||uid("pkg"),40),name:text(b.name,120),price:number(b.price),period:text(b.period||"starting",40),featured:Boolean(b.featured),visibility:b.visibility!==false,features:Array.isArray(b.features)?b.features.map(x=>text(x,150)).slice(0,20):String(b.features||"").split(",").map(x=>text(x,150)).filter(Boolean).slice(0,20)};
 if(name==="portfolio")return {id:text(b.id||uid("pf"),40),title:text(b.title,120),category:text(b.category,80),description:text(b.description,900),url:text(b.url,1800),technology:Array.isArray(b.technology)?b.technology.map(x=>text(x,80)).slice(0,10):String(b.technology||"").split(",").map(x=>text(x,80)).filter(Boolean).slice(0,10),image:safeImage(b.image||"")};
 if(name==="reviews")return {id:text(b.id||uid("rv"),40),name:text(b.name,80),rating:Math.min(5,Math.max(0,number(b.rating,5))),date:text(b.date||now().slice(0,10),20),text:text(b.text,1000),image:safeImage(b.image||"")};
 return null
}
async function api(req,res){
 const u=new URL(req.url,"http://localhost"),p=u.pathname,method=req.method;
 if(rateLimited(req,p))return json(res,429,{error:"Too many requests. Please try again shortly."});
 if(p==="/api/health"&&method==="GET")return json(res,200,{ok:true,service:"nexora-tech",time:now()});
 if(p==="/api/site"&&method==="GET")return json(res,200,readData());
 if(p==="/api/products"&&method==="GET")return json(res,200,readData().products);
 const prod=p.match(/^\/api\/products\/([^/]+)$/);if(prod&&method==="GET"){const x=readData().products.find(q=>q.id===prod[1]);return x?json(res,200,x):json(res,404,{error:"Product not found"})}
 if(p==="/api/search"&&method==="GET"){const q=text(u.searchParams.get("q"),100).toLowerCase(),d=readData();if(!q)return json(res,200,[]);const out=[];d.products.forEach(x=>{if((x.name+" "+x.category+" "+x.brand).toLowerCase().includes(q))out.push({type:"product",title:x.name,url:"/product/"+x.id,description:x.description})});d.services.forEach(x=>{if((x.title+" "+x.description).toLowerCase().includes(q))out.push({type:"service",title:x.title,url:"/services#"+x.id,description:x.description})});d.portfolio.forEach(x=>{if((x.title+" "+x.category+" "+x.description).toLowerCase().includes(q))out.push({type:"portfolio",title:x.title,url:"/portfolio#"+x.id,description:x.description})});return json(res,200,out.slice(0,20))}
 if(p==="/api/chat"&&method==="POST"){const b=await parseBody(req,50000),q=text(b.message,400),l=q.toLowerCase(),d=readData();let reply="I can help with products, PC builds, website packages, pricing, contact and basic FAQs.";if(/বাংলা|bangla|bengali/.test(l))reply="অবশ্যই। বাজেট, পণ্য, PC build বা website package বলুন—আমি guide করব।";else if(/website|web site|site|ওয়েব|web/.test(l))reply="Website-এর জন্য Basic, Business আর Premium E-commerce package আছে. আপনার budget আর business type বললে package shortlist করে দিতে পারি.";else if(/gaming pc|pc build|computer|gaming/.test(l)){const x=d.products.find(p=>p.category==="Desktop PC");reply=x?"Gaming PC: "+x.name+" — ৳"+Number(x.price).toLocaleString("en-BD")+". আপনার budget বলুন, আমি starter build সাজিয়ে দেব।":"Gaming PC option currently unavailable."}else if(/laptop/.test(l)){const x=d.products.find(p=>p.category==="Laptop");reply=x?"Laptop: "+x.name+" — ৳"+Number(x.price).toLocaleString("en-BD")+". কাজের ধরন ও budget বলুন।":"Laptop options currently unavailable."}else if(/price|৳|budget|dam|দাম/.test(l))reply="আপনার budget লিখুন, যেমন 100000 BDT. আমি matching products বা website package suggest করব.";else{const hits=d.products.filter(x=>(x.name+" "+x.category+" "+x.brand).toLowerCase().includes(l)).slice(0,3);if(hits.length)reply=hits.map(x=>x.name+" — ৳"+Number(x.price).toLocaleString("en-BD")).join(" | ")}return json(res,200,{reply})}
 if(p==="/api/contact"&&method==="POST"){const b=await parseBody(req,120000);if(!text(b.name,80)||!isEmail(b.email)||!text(b.message,2500))return json(res,422,{error:"Please provide your name, a valid email and a message."});const d=readData(),row={id:uid("MSG"),createdAt:now(),name:text(b.name,80),email:text(b.email,120),company:text(b.company,120),service:text(b.service,100),message:text(b.message,2500)};d.contacts.unshift(row);writeData(d);return json(res,201,{ok:true,id:row.id})}
 if(p==="/api/orders"&&method==="POST"){const b=await parseBody(req,160000);if(!Array.isArray(b.items)||!b.items.length)return json(res,422,{error:"Your cart is empty."});if(!text(b.customer?.name,80)||!text(b.customer?.phone,30)||!text(b.customer?.address,500))return json(res,422,{error:"Please complete the required delivery details."});const d=readData(),items=b.items.slice(0,30).map(i=>({id:text(i.id,40),name:text(i.name,160),price:number(i.price),qty:Math.max(1,Math.min(20,number(i.qty,1)))})),total=items.reduce((s,x)=>s+x.price*x.qty,0),o={id:uid("ORD"),createdAt:now(),customer:{name:text(b.customer.name,80),phone:text(b.customer.phone,30),email:text(b.customer.email,120),address:text(b.customer.address,500)},payment:text(b.payment||"Cash on delivery",80),items,total,status:"Pending"};d.orders.unshift(o);writeData(d);return json(res,201,{ok:true,orderId:o.id,status:o.status,total:o.total})}
 if(p==="/api/login"&&method==="POST"){const b=await parseBody(req,30000),user=text(b.username,80);if(!process.env.ADMIN_PASSWORD_HASH&&!process.env.ADMIN_PASSWORD)return json(res,500,{error:"Admin authentication is not configured."});if(user!==(process.env.ADMIN_USER||"admin")||!passwordOk(String(b.password||"")))return json(res,401,{error:"Invalid credentials"});const token=makeSession(user);res.writeHead(200,{"Content-Type":"application/json; charset=utf-8","Set-Cookie":"nx_admin="+token+"; HttpOnly; SameSite=Lax; Path=/; Max-Age=28800","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"});return res.end(JSON.stringify({ok:true,user}))}
 if(p==="/api/logout"&&method==="POST"){res.writeHead(200,{"Content-Type":"application/json","Set-Cookie":"nx_admin=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0"});return res.end(JSON.stringify({ok:true}))}
 if(p.startsWith("/api/admin/")){
  if(!requireAdmin(req,res))return;
  const parts=p.slice("/api/admin/".length).split("/"),name=parts[0],id=parts[1],d=readData();
  if(name==="dashboard"&&method==="GET")return json(res,200,{products:d.products.length,orders:d.orders.length,reviews:d.reviews.length,portfolio:d.portfolio.length,services:d.services.length,packages:d.packages.length,contacts:d.contacts.length});
  if(name==="site"&&method==="GET")return json(res,200,d.settings);
  if(name==="site"&&method==="PUT"){const b=await parseBody(req,1600000),s=d.settings;["brand","maker","sponsor","tagline","heroTitle","heroDescription","ctaText","phone","whatsapp","messenger","email","address"].forEach(k=>{if(b[k]!==undefined)s[k]=text(b[k],k==="heroDescription"?800:220)});if(b.heroImage)s.heroImage=safeImage(b.heroImage);if(b.socials)s.socials=Object.assign({},s.socials||{},b.socials);writeData(d);return json(res,200,s)}
  if(name==="orders"&&method==="GET")return json(res,200,d.orders);
  if(name==="contacts"&&method==="GET")return json(res,200,d.contacts);
  if(["products","services","packages","portfolio","reviews"].includes(name)){
   const arr=d[name]||[];
   if(method==="GET")return json(res,200,arr);
   if(method==="POST"){try{const row=norm(name,await parseBody(req,2000000));if((name==="products"&&!row.name)||(["services","portfolio"].includes(name)&&!row.title)||(["packages","reviews"].includes(name)&&!row.name&&name==="packages"))throw new Error("Required fields are missing");arr.unshift(row);d[name]=arr;writeData(d);return json(res,201,row)}catch(e){return json(res,422,{error:e.message})}}
   if(id){const idx=arr.findIndex(x=>String(x.id)===String(id));if(idx<0)return json(res,404,{error:"Item not found"});if(method==="PUT"){try{const row=norm(name,Object.assign({},arr[idx],await parseBody(req,2000000),{id:arr[idx].id}));arr[idx]=row;writeData(d);return json(res,200,row)}catch(e){return json(res,422,{error:e.message})}}if(method==="DELETE"){arr.splice(idx,1);writeData(d);return json(res,200,{ok:true})}}
  }
  if(name==="orders"&&id&&method==="PUT"){const o=d.orders.find(x=>x.id===id);if(!o)return json(res,404,{error:"Order not found"});const b=await parseBody(req,30000);o.status=text(b.status||o.status,40);writeData(d);return json(res,200,o)}
  if(name==="orders"&&id&&method==="DELETE"){const idx=d.orders.findIndex(x=>x.id===id);if(idx<0)return json(res,404,{error:"Order not found"});d.orders.splice(idx,1);writeData(d);return json(res,200,{ok:true})}
  return json(res,404,{error:"Admin route not found"});
 }
 return null;
}
function sendStatic(req,res){const u=decodeURIComponent(String(req.url||"/").split("?")[0]);const rel=u==="/favicon.ico"?"/assets/nexora-web-logo.svg":u,file=path.normalize(path.join(PUBLIC,rel));if(!file.startsWith(PUBLIC+path.sep))return html(res,403,"Forbidden");fs.stat(file,(err,st)=>{if(err||!st.isFile())return html(res,404,render404());const ext=path.extname(file).toLowerCase();res.writeHead(200,{"Content-Type":TYPES[ext]||"application/octet-stream","Cache-Control":ext===".js"||ext===".css"?"public, max-age=3600":"public, max-age=86400"});fs.createReadStream(file).pipe(res)})}
const server=http.createServer(async(req,res)=>{try{if(req.url==="/robots.txt"){res.writeHead(200,{"Content-Type":"text/plain; charset=utf-8"});return res.end("User-agent: *\nAllow: /\nSitemap: /sitemap.xml\n")}if(req.url==="/sitemap.xml"){const routes=["/","/shop","/services","/packages","/portfolio","/reviews","/about","/contact","/cart","/checkout","/search","/builder"];res.writeHead(200,{"Content-Type":"application/xml; charset=utf-8"});return res.end("<?xml version='1.0' encoding='UTF-8'?><urlset xmlns='http://www.sitemaps.org/schemas/sitemap/0.9'>"+routes.map(x=>"<url><loc>"+x+"</loc></url>").join("")+"</urlset>")}if(req.url.startsWith("/api/")){const out=await api(req,res);if(out!==null)return}if(req.method==="GET"){const p=pageFor(req.url);if(p&&p.admin){if(!sessionUser(req))return html(res,200,"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>NEXORA ADMIN LOGIN</title><link rel='stylesheet' href='/style.css'></head><body class='adminLoginBody'><div class='loginCard'><div class='brand'><span class='brandLogo'>N</span><span><b>NEXORA</b><em>ADMIN</em></span></div><div class='eyebrow'>SECURE ADMIN ACCESS</div><h1>Control your store.</h1><p>Manage products, packages, portfolio, reviews, orders and website settings.</p><form id='loginForm'><label>Username<input name='username' value='admin' required></label><label>Password<input name='password' type='password' required></label><button class='btn primary' type='submit'>Sign in ↗</button><div class='notice' id='loginNotice'></div></form></div><script src='/admin.js' defer></script></body></html>");return html(res,200,p.body)}if(p)return html(res,200,p.body)}sendStatic(req,res)}catch(e){if(!res.headersSent)json(res,500,{error:"Server error"})}}).listen(PORT,"0.0.0.0",()=>console.log("NEXORA TECH running on "+PORT));
